# Generated by Django 5.0.6 on 2025-06-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
