# Generated by Django 5.0.6 on 2025-06-09 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAccounts', '0002_user_city_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='server@gytny.co.za', max_length=254, unique=True),
        ),
    ]
