# Generated by Django 5.0.6 on 2025-07-11 21:06

import AuthAccounts.models
from django.db import migrations, models
import secrets

def generate_user_id():
    return secrets.token_hex(9).upper()

class Migration(migrations.Migration):
    dependencies = [
        ('AuthAccounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(
                max_length=18,
                unique=True,
                null=True,  # Allow null temporarily
                blank=True,
            ),
        ),
    ]