# Generated by Django 5.0.6 on 2025-07-11 21:21

import AuthAccounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAccounts', '0005_populate_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(default=AuthAccounts.models.generate_user_id, editable=False, max_length=18, unique=True),
        ),
    ]
