# Generated by Django 5.0.6 on 2025-07-31 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAccounts', '0007_user_token_created_at_user_verification_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccountPasswordResetPiny',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_pins', to=settings.AUTH_USER_MODEL, to_field='user_id')),
            ],
        ),
    ]
