# Generated by Django 5.0.6 on 2025-08-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAccounts', '0010_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='verification_token',
        ),
        migrations.AddField(
            model_name='user',
            name='verification_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
