# Generated by Django 5.0.6 on 2025-08-22 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthAccounts', '0011_remove_user_verification_token_user_verification_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
