# Generated by Django 5.0.6 on 2025-02-05 13:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DisLikes',
            new_name='DisLike',
        ),
        migrations.RenameModel(
            old_name='Likes',
            new_name='Like',
        ),
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
        migrations.RenameModel(
            old_name='Shares',
            new_name='Share',
        ),
    ]
