# Generated by Django 5.0.6 on 2025-02-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0002_rename_dislikes_dislike_rename_likes_like_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='user',
            new_name='guide',
        ),
    ]
