# Generated by Django 5.0.6 on 2025-02-09 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_rename_user_route_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
