# Generated by Django 5.0.6 on 2025-02-12 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roommessage',
            name='content',
        ),
        migrations.AddField(
            model_name='roommessage',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='content', to='community.content'),
        ),
    ]
