# Generated by Django 5.0.6 on 2025-03-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_roommessage_content_roommessage_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='current_location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='price',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
