# Generated by Django 5.0.6 on 2025-06-28 22:03
import secrets

from django.db import migrations

def generate_group_id():
    return secrets.token_hex(4).upper()  # 8-char hex → 16-char when uppercase

def populate_ids(apps, schema_editor):
    ChatRoom = apps.get_model('community', 'ChatRoom')
    for room in ChatRoom.objects.all():
        if room.group_id == 'TEMP_ID':
            room.group_id = generate_group_id()
            room.save()

class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_remove_roommessage_content_and_more'),
    ]

    operations = [
        migrations.RunPython(populate_ids),
    ]
