# Generated by Django 5.0.6 on 2025-07-11 11:29

import community.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_populate_group_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='group_id',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='chat_id',
            field=models.CharField(default=community.models.generate_group_id, editable=False, max_length=16, unique=True),
        ),
    ]
