# Generated by Django 5.0.6 on 2025-07-11 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_populate_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='group_name',
            field=models.CharField(blank=True, db_index=True, max_length=200, null=True),
        ),
    ]
