# Generated by Django 5.0.6 on 2025-07-11 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_chatroom_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roommessage',
            name='chat_room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='community.chatroom', to_field='chat_id'),
        ),
    ]
